/**
 * Icon preloading utilities.
 *
 * `Icon` (and every component built on top of it) fetches its SVG data from
 * the Iconify API the first time a given icon name is rendered, which can
 * cause a brief layout shift / "pop-in" the first time an icon appears.
 * Calling `preloadIcons()` once during app initialization (e.g. the root
 * `+layout.svelte`, alongside `loadPlatformPolyfills()`) kicks off those
 * network requests early so icon data is already cached by the time
 * components mount.
 *
 * `DEFAULT_PRELOAD_ICONS` is generated by `scripts/generate-icon-list.mjs`
 * (`pnpm run generate:icons`), which scans every component under
 * `src/lib/components` for icon names it renders itself (literal
 * `<Icon name="...">` usages and default values of icon-shaped props).
 * It cannot see icon names that are only known at runtime — e.g. names
 * supplied through a consumer's own `menu`/`items` data — so apps with
 * their own icon usage should pass their own list (optionally spread
 * together with `DEFAULT_PRELOAD_ICONS`) to `preloadIcons()`.
 */
import { loadIcons } from "@iconify/svelte/dist/functions"
import { get } from "svelte/store"
import { iconConfig } from "./iconManager.js"

/**
 * Icon names (in `iconset:name` form) rendered internally by Twintrinsic's
 * own components. Regenerate with `pnpm run generate:icons`.
 */
export const DEFAULT_PRELOAD_ICONS: string[] = [
  // AUTO-GENERATED-ICONS-START — do not edit by hand, run `pnpm run generate:icons`
  "tabler:alert-circle",
  "tabler:alert-triangle",
  "tabler:bell",
  "tabler:check",
  "tabler:check-circle",
  "tabler:chevron-down",
  "tabler:chevron-left",
  "tabler:chevron-right",
  "tabler:clipboard",
  "tabler:circle-check",
  "tabler:home",
  "tabler:info-circle",
  "tabler:menu-2",
  "tabler:moon",
  "tabler:search",
  "tabler:settings",
  "tabler:star",
  "tabler:star-filled",
  "tabler:sun",
  "tabler:x",
  // AUTO-GENERATED-ICONS-END
]

/**
 * Kick off Iconify data fetches for a list of icon names ahead of time so
 * `Icon` can render them synchronously (from cache) once components mount.
 *
 * Bare names (no `iconset:` prefix) are resolved against the current
 * global default iconset (see `setIconset`) at the time this is called.
 *
 * @param icons - Icon names to preload, with or without an `iconset:` prefix. Defaults to `DEFAULT_PRELOAD_ICONS`.
 */
export function preloadIcons(icons: string[] = DEFAULT_PRELOAD_ICONS): void {
  const defaultIconset = get(iconConfig).defaultIconset
  const qualifiedNames = icons.map((icon) => (icon.includes(":") ? icon : `${defaultIconset}:${icon}`))
  loadIcons(qualifiedNames)
}
