<!--
@component
CompatibilityMatrix - renders a cross-browser support table for the
Tier 0 "Chrome-only" platform APIs tracked in
docs/plans/HTML_SEMANTIC_REPLACEMENT_PLAN.md.

Data is generated by `pnpm test:compat` (Playwright, run against
Chromium/Firefox/WebKit — see tests/compat/browser-support.test.ts) and
merged into `static/browser-compat.json` by
scripts/merge-browser-compat.mjs. This component fetches that file at
runtime, so the matrix always reflects the last time the compat suite ran
in CI without requiring a rebuild of the docs site.

Usage:
```svelte
<script>
  import CompatibilityMatrix from "$lib/components/CompatibilityMatrix/CompatibilityMatrix.svelte"
</script>

// Show every tracked feature
<CompatibilityMatrix />

// Show only the features relevant to one component
<CompatibilityMatrix features={["Popover API", "CSS Anchor Positioning"]} />
```
-->
<script module lang="ts">
export const propsMetadata = [
  { name: "features", type: "string[]", description: "Feature names to include; omit to show every tracked feature", optional: true },
  { name: "src", type: "string", description: "URL to fetch the compatibility JSON from", default: "\"/browser-compat.json\"", optional: true },
];
</script>

<script lang="ts">
interface CompatData {
  generatedAt: string;
  browsers: string[];
  features: Record<string, Record<string, boolean>>;
}

interface Props {
  /** Feature names to include; omit to show every tracked feature */
  features?: string[];
  /** URL to fetch the compatibility JSON from */
  src?: string;
}

const { features = undefined, src = "/browser-compat.json" }: Props = $props();

let data = $state<CompatData | null>(null);
let error = $state<string | null>(null);

/**
 * Fetch and parse the browser compatibility JSON generated by the
 * cross-browser Playwright suite.
 */
async function loadCompatData() {
  try {
    const response = await fetch(src);
    if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
    data = (await response.json()) as CompatData;
  } catch (err) {
    error = err instanceof Error ? err.message : String(err);
  }
}

$effect(() => {
  loadCompatData();
});

const browserLabels: Record<string, string> = {
  chromium: "Chrome",
  firefox: "Firefox",
  webkit: "Safari",
};

const rows = $derived.by(() => {
  if (!data) return [];
  const names = features ?? Object.keys(data.features);
  return names.filter((name) => name in data!.features);
});
</script>

{#if error}
  <p class="compat-matrix-error" role="status">
    Couldn't load browser compatibility data: {error}
  </p>
{:else if !data}
  <p class="compat-matrix-loading" role="status">Loading browser compatibility data…</p>
{:else if rows.length === 0}
  <p class="compat-matrix-empty" role="status">No matching compatibility data available.</p>
{:else}
  <div class="compat-matrix">
    <table>
      <caption class="sr-only">Browser compatibility for modern platform APIs</caption>
      <thead>
        <tr>
          <th scope="col">Feature</th>
          {#each data.browsers as browser (browser)}
            <th scope="col">{browserLabels[browser] ?? browser}</th>
          {/each}
        </tr>
      </thead>
      <tbody>
        {#each rows as name (name)}
          <tr>
            <td class="compat-matrix-feature"><code>{name}</code></td>
            {#each data.browsers as browser (browser)}
              {@const supported = data.features[name]?.[browser]}
              <td class="compat-matrix-cell">
                <span
                  class="compat-matrix-icon"
                  class:supported
                  class:unsupported={!supported}
                  role="img"
                  aria-label={supported ? "Supported" : "Not supported"}
                >
                  {supported ? "✓" : "✗"}
                </span>
              </td>
            {/each}
          </tr>
        {/each}
      </tbody>
    </table>
    <p class="compat-matrix-generated">
      Generated {new Date(data.generatedAt).toLocaleDateString()} via <code>pnpm test:compat</code>.
    </p>
  </div>
{/if}

<style lang="postcss">
  @reference "../../twintrinsic.css";

  .sr-only {
    @apply absolute w-px h-px p-0 -m-px overflow-hidden whitespace-nowrap border-0;
    clip: rect(0, 0, 0, 0);
  }

  .compat-matrix {
    @apply my-4 overflow-x-auto rounded-lg border border-border;
  }

  table {
    @apply w-full border-collapse;
  }

  th {
    @apply px-4 py-2 text-left text-sm font-medium bg-surface border-b border-border;
  }

  td {
    @apply px-4 py-2 border-b border-border align-middle;
  }

  .compat-matrix-feature {
    @apply whitespace-nowrap;
  }

  .compat-matrix-cell {
    @apply text-center;
  }

  .compat-matrix-icon {
    @apply inline-flex items-center justify-center font-bold;
  }

  .compat-matrix-icon.supported {
    @apply text-success;
  }

  .compat-matrix-icon.unsupported {
    @apply text-error-bold;
  }

  .compat-matrix-generated {
    @apply px-4 py-2 text-xs text-muted;
  }

  .compat-matrix-error {
    @apply text-sm text-error-bold;
  }

  .compat-matrix-loading,
  .compat-matrix-empty {
    @apply text-sm text-muted;
  }
</style>
