#!/usr/bin/env node
/**
 * Validates the published subpath exports map (package.json `exports`).
 *
 * Guards against the two regression classes found in Phase 9.7c:
 *  1. Export targets that don't exist on disk — the doubled
 *     `components/components/` prefix broke all 87 component subpaths
 *     (`twintrinsic/components/Button` was unresolvable) while builds,
 *     packs, and publint stayed green.
 *  2. Subpath modules whose generated `.d.ts` files fail a strict
 *     typecheck (e.g. TS2440 self-import conflicts in recursive
 *     components, TS2882 side-effect CSS imports).
 *
 * Steps:
 *  1. Build `dist/` via `svelte-package` so the check runs against the
 *     real published artifact.
 *  2. Existence check: every `types`/`svelte`/`default` target must exist
 *     and live under `./dist/` (matching `files: ["dist"]`).
 *  3. Strict type check: generates a temporary module that namespace-
 *     imports every subpath (self-reference resolution through the
 *     package's own exports map) plus the known `<script module>` type
 *     exports, then runs `tsc --noEmit` with `skipLibCheck: false` so
 *     errors *inside* the library's `.d.ts` files are caught, not just
 *     usage errors.
 *
 * Usage: `pnpm validate:exports` (requires devDependencies installed).
 * Exits non-zero on any failure. Temporary files are cleaned up.
 */
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const pkgPath = path.join(root, "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const tmpDir = path.join(root, ".tmp-exports-check");

const fail = (msg) => {
	console.error(`[validate-exports] FAIL: ${msg}`);
	process.exitCode = 1;
};
const log = (msg) => console.log(`[validate-exports] ${msg}`);

/** 1. Build the artifact so the check runs against the real dist output. */
log("building dist via svelte-package...");
try {
	execSync("pnpm exec svelte-kit sync && pnpm exec svelte-package", {
		cwd: root,
		stdio: "inherit",
	});
} catch {
	fail("svelte-package build failed");
	process.exit(1);
}

/** 2. Existence check — every target must exist under ./dist/. */
const targets = [];
for (const [sub, conds] of Object.entries(pkg.exports ?? {})) {
	const entries =
		typeof conds === "string" ? [["default", conds]] : Object.entries(conds);
	for (const [cond, target] of entries) targets.push({ sub, cond, target });
}

const missing = targets.filter(({ target }) => !existsSync(path.join(root, target)));
const notDist = targets.filter(({ target }) => !target.startsWith("./dist/"));
const filesField = Array.isArray(pkg.files) ? pkg.files : [];
const distInFiles = filesField.includes("dist");

if (missing.length || notDist.length) {
	for (const { sub, cond, target } of missing) {
		fail(`target does not exist — ${sub} [${cond}] -> ${target}`);
	}
	for (const { sub, cond, target } of notDist) {
		fail(`target outside ./dist/ (files: ["dist"] would exclude it) — ${sub} [${cond}] -> ${target}`);
	}
} else {
	log(`existence OK — ${targets.length} targets, all under ./dist/`);
}
if (!distInFiles) {
	fail(`package.json "files" must include "dist" (currently: ${JSON.stringify(pkg.files)})`);
}

/** 3. Strict type check via self-reference imports of every subpath. */
const importableSubs = Object.keys(pkg.exports ?? {}).filter(
	(sub) => sub !== "./twintrinsic.css", // CSS can't be type-imported; existence is checked above
);

/**
 * Types exported from `<script module>` blocks — the type-availability
 * surface the audit in Phase 9.7c verified. Keep this in sync when a
 * component's module-script type exports change (the check then guards
 * the new names).
 */
const MODULE_SCRIPT_TYPES = {
	"./components/App": ["AppProps"],
	"./components/AutoComplete": ["ItemTemplateValue"],
	"./components/BottomBar": ["BottomBarProps"],
	"./components/DataTable": ["ColumnDef"],
	"./components/Input": ["InputProps"],
	"./components/Panel": ["PanelProps"],
	"./components/Sidebar": ["SidebarProps"],
	"./components/TreeMenu": ["MenuItem"],
};

const lines = [];
lines.push("// AUTO-GENERATED by scripts/validate-exports.mjs — do not edit.");
lines.push("");
for (const sub of importableSubs) {
	const id = "Sub_" + sub.replace(/[^\w$]+/g, "_");
	const spec = sub === "." ? "twintrinsic" : `twintrinsic${sub.slice(1)}`;
	lines.push(`import * as ${id} from "${spec}";`);
	lines.push(`void ${id};`);
}
lines.push("");
for (const [sub, names] of Object.entries(MODULE_SCRIPT_TYPES)) {
	const spec = `twintrinsic${sub.slice(1)}`;
	lines.push(`import type { ${names.join(", ")} } from "${spec}";`);
}
lines.push("");

mkdirSync(tmpDir, { recursive: true });
writeFileSync(path.join(tmpDir, "exports-check.ts"), lines.join("\n"));
// Ambient css module declaration in its own import-free file (same shape
// as `vite/client`): css side-effect imports in library d.ts files (e.g.
// Map's `import 'leaflet/dist/leaflet.css'`) are valid at runtime and
// typed away by real consumers' css module declarations. Non-css asset
// imports are still caught by this check.
writeFileSync(
	path.join(tmpDir, "ambient.d.ts"),
	'// Mirrors the `vite/client` css module declarations real consumers have.\ndeclare module "*.css";\n',
);
writeFileSync(
	path.join(tmpDir, "tsconfig.json"),
	JSON.stringify(
		{
			compilerOptions: {
				module: "esnext",
				moduleResolution: "bundler",
				target: "es2022",
				lib: ["es2022", "dom"],
				strict: true,
				noEmit: true,
				skipLibCheck: false,
				types: [],
			},
			include: ["exports-check.ts", "ambient.d.ts"],
		},
		null,
		2,
	),
);

log(`type-checking ${importableSubs.length} subpaths with tsc (skipLibCheck: false)...`);
let tscOutput = "";
try {
	tscOutput = execSync("pnpm exec tsc -p .tmp-exports-check/tsconfig.json", {
		cwd: root,
		encoding: "utf8",
		stdio: ["ignore", "pipe", "pipe"],
	});
} catch (e) {
	tscOutput = String(e.stdout ?? "") + String(e.stderr ?? "");
}
rmSync(tmpDir, { recursive: true, force: true });

if (tscOutput.trim()) {
	fail("strict tsc found errors in exported subpath types:");
	console.error(tscOutput.trim());
} else {
	log("type check OK — all subpaths resolve and their .d.ts files are clean");
}

if (process.exitCode) {
	console.error(`\n[validate-exports] failed — see errors above.`);
	process.exit(process.exitCode);
}
console.log("\n[validate-exports] all checks passed.");
